scinote-eln/scinote-api-docs

source/includes/_inventories.md
source/includes/_inventory_column_list_items.md
source/includes/_inventory_columns.md
source/includes/_inventory_items.md
source/includes/_results.md
source/includes/_teams.md
source/index.html.md
source/stylesheets/screen.css.scss

Updates to the documentation, relates to [PR on Core](https://github.com/biosistemika/scinote-web/pull/1327).

Multiple fixes to bring the API to the JSONAPI standard [SCI-2768]

---

source/includes/_status.md
source/index.html.md

https://github.com/biosistemika/scinote-web/pull/1367

Add missing health/status endpoints

---

source/includes/_inventory_cells.md
source/includes/_inventory_columns.md
source/includes/_inventory_items.md
source/includes/_project_comments.md
source/includes/_project_users.md
source/includes/_projects.md
source/includes/_reports.md
source/includes/_task_activities.md
source/includes/_task_inventory_items.md
source/includes/_task_users.md
source/includes/_users.md

Update docs to match the implementation

---

source/index.html.md

Add ToS link to index.html

---

source/index.html.md

Fix pagination wording

---

source/includes/_project_activities.md
source/includes/_task_activities.md

Update documentation with new examples for activities [SCI-3295]

Update documentation with new examples for activities [SCI-3295]

---

source/includes/_tasks.md

[JIRA task](https://biosistemika.atlassian.net/browse/SCI-3834)
[SciNote PR](https://github.com/biosistemika/scinote-web/pull/2051)

Add create task API endpoint

---

source/includes/_attachments.md
source/index.html.md

[JIRA task 3836](https://biosistemika.atlassian.net/browse/SCI-3836)

Attachments API endpoint [SCI-3836]

---

source/includes/_results.md

[JIRA task 3837](https://biosistemika.atlassian.net/browse/SCI-3837)
[JIRA task 3838](https://biosistemika.atlassian.net/browse/SCI-3838)

Result(file) create/update API endpoint

---

source/includes/_inventory_column_status_items.md
source/index.html.md

Docs for [this PR](https://github.com/biosistemika/scinote-web/pull/2166)

Add StatusItems API endpoints [SCI-3996]

---

source/includes/_inventory_column_checklist_items.md
source/includes/_inventory_columns.md
source/index.html.md

Jira ticket: [SCI-4456](https://biosistemika.atlassian.net/browse/SCI-4456)

Add documentaton for inventory column checklist items [SCI-4456]

---

source/includes/_inventories.md
source/includes/_inventory_items.md

Update documentation for [SCI-4741](https://github.com/biosistemika/scinote-web/pull/2679)

Update API docs for active repos and rows [SCI-4741]

---

source/includes/_inventory_columns.md

[SCI-4548](https://biosistemika.atlassian.net/browse/SCI-4548)
Add metadata attribute for number column type for post/patch column

Add metadata attribute for number column type for post/patch column [SCI-4548]

---

source/includes/_attachments.md
source/includes/_results.md

Jira ticket: [SCI-4813](https://biosistemika.atlassian.net/browse/SCI-4813)

Update API endpoints for File Results and Attachments [SCI-4813]

---

source/includes/_checklist_items.md
source/includes/_checklists.md
source/includes/_protocol_steps.md
source/includes/_tables.md
source/includes/_tasks.md
source/index.html.md

Include new endpoints for steps, checklist, checklist items, tables

Include new endpoints for steps, checklist, checklist items, tables [SCI-4776]

---

source/includes/_tasks.md
source/includes/_workflow_statuses.md
source/includes/_workflows.md
source/index.html.md

https://biosistemika.atlassian.net/browse/SCI-4831

Add documentation for new workflow [SCI-4831]

---

source/includes/_project_users.md

https://biosistemika.atlassian.net/browse/SCI-5001

Add Endpoins for Project Membership manipulation [SCI-5001]

---

source/includes/_connections.md

Added docs for the connections API

Added docs for connections API [SCI-6087]

---

source/includes/_task_inventory_items.md

Added docs for stock consumption.

Update task inventory item docs [SCI-6642]

---

source/includes/_webhooks.md
source/index.html.md

Add webhook docs [SCI-6397]

---

source/includes/_task_assignments.md
source/index.html.md

Add task assignment API endpoint documentation

Add task assignment documentation [SCI-6846]

---

source/includes/_protocol_steps.md

Add docs for reorder endpoints

Add docs for reorder endpoints [SCI-6891][SCI-6892]

---

source/includes/_protocol_templates.md
source/index.html.md

Add retrieving of protocol templates API endpoint

Add retrieving of protocol templates API endpoint [SCI-7456]

---

source/includes/_checklists.md
source/includes/_experiments.md
source/includes/_projects.md
source/includes/_step_texts.md
source/includes/_tables.md
source/includes/_tasks.md
source/includes/_users.md

Fix documentation for changed API endpoints [SCI-8839]

---

Dockerfile
README.md
README.old.md
docker-compose.yml

It's about time we do this. 
I've added proper docker-compose config, so developers can preview their changes, added readme as well.

Added docker-compose configuration, added proper readme

---

source/includes/_inventory_item_relationships.md
source/index.html.md

Added API V2 docs for the item relationships to create and delete requests

Implement API V2 docs fr item relationships [SCI-10038]

---

source/includes/_checklist_items_v1.md
source/includes/_checklist_items_v2.md
source/includes/_checklists_v1.md
source/includes/_checklists_v2.md
source/includes/_step_texts_v1.md
source/includes/_step_texts_v2.md
source/includes/_tables_v1.md
source/includes/_tables_v2.md

Add docs for v2 step elements [SCI-9652]

---

source/index.html.md

Add API key documentation [SCI-10775]

---

source/includes/_protocol_steps_v2.md
source/includes/_step_form_responses.md
source/index.html.md

Add docs for v2 step form response elements [SCI-11850]

Add docs for v2 step form response elements [SCI-11850]

---

source/includes/_inventory_items.md

Add archived filter to inventory items [SCI-11770]

Add archived filter to inventory items [SCI-11770]

---

source/includes/_step_form_responses.md
source/index.html.md

Fix step form responses header name [SCI-11850]

Fix step form responses header name [SCI-11850]
